const businesses = [
  {
    "id": 12,
    "logo": "https://res.cloudinary.com/digital-cats/image/upload/v1680872001/Bellos/Bellos_3_tqutjk.png",
    "image": "https://res.cloudinary.com/digital-cats/image/upload/v1680872017/Bellos/Ramadan_BOxes_1_juj7ww.png",
    "category": "East African Kitchen",
    "businessName": "Bellos Kitchen",
    "address": "208 Claremont Rd, Manchester M14 4TS",
    "description": "Soulful and savory dishes that warm your heart and soul. Celebrate the richness of our heritage through every bite",
    "originId": [],
    "contactNumber": "0161 465 0114",
    "contactEmail": "belloskitchen@gmail.com",
    "userId": "123",
    "isPortrait": false,
    "isAd": false,
    saves: 5800000,

  },
  {
    "id": 13,
    "logo": "https://www.nicepng.com/png/detail/464-4647468_uber-logo-gray-social-media-icons-png.png",
    "image": "https://cdn-img.prettylittlething.com/b/4/3/c/b43c85a2168c0954758b581879b968444dd3ac77_cnc5313_1.jpg",
    "category": "East African Restaurant",
    "businessName": "Ayas Restaurant",
    "address": "456 Main St, City, State, Zip",
    "description": "Captivating scents that empower and uplift. Crafted with care and inspired by the beauty and strength of black women.",
    "originId": [],
    "contactNumber": "555-5678",
    "contactEmail": "business2@example.com",
    "userId": "2",
    "isPortrait": true,
    "isAd": false,
    saves: 850000,
  },
  {
    "id": 14,
    "logo": "https://www.nicepng.com/png/detail/464-4647468_uber-logo-gray-social-media-icons-png.png",
    "image": "https://makeagency.co.uk/wp-content/uploads/2023/02/make-agency-web-trends2023-590x357.jpg",
    "category": "Beauty and Personal Care",
    "businessName": "Make Agency",
    "address": "789 Main St, City, State, Zip",
    "description": "Captivating scents that empower and uplift. Crafted with care and inspired by the beauty and strength of black women",
    "originId": [],
    "contactNumber": "555-9012",
    "contactEmail": "business3@example.com",
    "userId": "3",
    "isPortrait": false,
    "isAd": false,
    saves: 3809900,
  },
  {
    "id": 15,
    "logo": "https://10619-2.s.cdn12.com/rests/original/110_503875292.jpg",
    "image": "https://res.cloudinary.com/digital-cats/image/upload/v1681779665/Nigerian%20Bar/Food%20pics/hq3_bz6jv4.jpg",
    "category": "Nigerian Restaurant",
    "businessName": "H.Q. Nigerian Restaurant",
    "address": "789 Main St, City, State, Zip",
    "description": "A Fresh Taste of Naija Cuisines at Your Table We Cater For All Occassion, 4pm-11pm, Mon-Sun Afrobeats YouOrder! WeCreate",
    "originId": [],
    "contactNumber": "0161 425 5080",
    "contactEmail": "general@hq-manchester.co.uk",
    "userId": "3",
    "isPortrait": true,
    "isAd": false,
    saves: 158000,
  },
  {
    "id": 16,
    "logo": "https://www.nicepng.com/png/detail/464-4647468_uber-logo-gray-social-media-icons-png.png",
    "image": "https://i8.amplience.net/i/jpl/jd_637232_e?qlt=92&w=750&h=531&v=1&fmt=auto",
    "category": "Food and Beverage",
    "businessName": "Boohoo",
    "address": "1234 First St, City, State, Zip",
    "description": "Captivating scents that empower and uplift. Crafted with care and inspired by the beauty and strength of black women",
    "originId": [],
    "contactNumber": "555-3456",
    "contactEmail": "business4@example.com",
    "userId": "4",
    "isPortrait": true,
    "isAd": false,
    saves: 1200000,
  },
  {
    "id": 17,
    "logo": "https://play-lh.googleusercontent.com/YNxY4PM-s4YhSdXkYikLCMuu_mrbHQKOB2R0QNEnKM5ly-dEGqiqn2H_J8D5XyFdpw",
    "image": "https://cdn-img.prettylittlething.com/3/f/9/6/3f96423becddfc12c87f21b6f4795dbf6252c7c9_cnc6624_1.jpg?imwidth=400",
    "category": "Fashion and Clothing",
    "businessName": "Pretty Litle Things",
    "address": "5678 Second St, City, State, Zip",
    "description": "Captivating scents that empower and uplift. Crafted with care and inspired by the beauty and strength of black women",
    "originId": [],
    "contactNumber": "555-6789",
    "contactEmail": "business5@example.com",
    "userId": "5",
    "isPortrait": true,
    saves: 543000,
  },
  {
    "id": 18,
    "logo": "https://res.cloudinary.com/digital-cats/image/upload/v1692105124/Ayas%20Grill/A_1_f0yt0m.png",
    "image": "https://res.cloudinary.com/digital-cats/image/upload/v1692105533/Ayas%20Grill/Slow-cooked-braised-lamb-shanks-SQ-735x735_rq3z6v.jpg",
    "category": "Somaili Food",
    "businessName": "Ayas Restaurant",
    "address": "231 Great Western St, Manchester M14 4LG",
    "description": "Great Food For A Great Mood, Enjoy dishes that warm your heart and soul. Celebrate the richness of our heritage through every bite",
    "originId": [],
    "contactNumber": "07984637030",
    "contactEmail": "Ayasmcr@gmail.com",
    "userId": "6",
    "isPortrait": true,
    saves: 14800000,
  },
  {
    "id": 19,
    "logo": "https://www.nicepng.com/png/detail/464-4647468_uber-logo-gray-social-media-icons-png.png",
    "image": "https://res.cloudinary.com/digital-cats/image/upload/v1667959613/Canva/Digital%20Cats/WEB_originId_v6zosj.png",
    "category": "Health and Wellness",
    "businessName": "Tesco",
    "address": "3456 Fourth St, City, State, Zip",
    "description": "Captivating scents that empower and uplift. Crafted with care and inspired by the beauty and strength of black women",
    "originId": [],
    "contactNumber": "555-5678",
    "contactEmail": "business7@example.com",
    "userId": "business7",
    "isPortrait": false,
    saves: 45000
  }
]

export default businesses