const data = {
  businesses: [
    {
      "id": 12,
      "image": "https://res.cloudinary.com/digital-cats/image/upload/v1680872017/Bellos/Ramadan_BOxes_1_juj7ww.png",
      "title": "Bellos Kitchen",
      "businessName": "Bellos",
      "address": "123 Main St, City, State, Zip",
      "description": "Soulful and savory dishes that warm your heart and soul. Celebrate the richness of our heritage through every bite",
      "originals": ["Service 1", "Service 2", "Service 3"],
      "contactNumber": "555-1234",
      "contactEmail": "business1@example.com",
      "username": "business1",
      "password": "password1",
      "isPortrait": false,
      "isAd": false,
      "store": "Bellos",
      saves: 5800000,

    },
    {
      "id": 13,
      "image": "https://cdn-img.prettylittlething.com/b/4/3/c/b43c85a2168c0954758b581879b968444dd3ac77_cnc5313_1.jpg",
      "title": "Digital Cats",
      "businessName": "Pretty Litle Things",
      "address": "456 Main St, City, State, Zip",
      "description": "Captivating scents that empower and uplift. Crafted with care and inspired by the beauty and strength of black women.",
      "originals": ["Service 4", "Service 5", "Service 6"],
      "contactNumber": "555-5678",
      "contactEmail": "business2@example.com",
      "username": "business2",
      "password": "password1",
      "isPortrait": true,
      "isAd": false,
      saves: 850000,
    },
    {
      "id": 14,
      "image": "https://makeagency.co.uk/wp-content/uploads/2023/02/make-agency-web-trends2023-590x357.jpg",
      "title": "Beauty and Personal Care",
      "businessName": "Make Agency",
      "address": "789 Main St, City, State, Zip",
      "description": "Passionate curator for black-owned businesses, prioritizing sustainability & social responsibility. Join me in creating an inclusive economy & supporting diverse entrepreneurs. Let's build a thriving ecosystem of black-owned businessesBusiness 3",
      "originals": ["SEO ", " MARKETING", " WEBSITES"],
      "contactNumber": "555-9012",
      "contactEmail": "business3@example.com",
      "username": "business3",
      "password": "password1",
      "isPortrait": false,
      "isAd": false,
      "store": "Make Agency",
      saves: 3809900,
    },
    {
      "id": 15,
      "image": "https://images.pexels.com/photos/1400249/pexels-photo-1400249.jpeg?cs=srgb&dl=pexels-mihai-vlasceanu-1400249.jpg&fm=jpg",
      "title": "Beauty and Personal Care",
      "businessName": "Mihai",
      "address": "789 Main St, City, State, Zip",
      "description": "Passionate curator for black-owned businesses, prioritizing sustainability & social responsibility. Join me in creating an inclusive economy & supporting diverse entrepreneurs. Let's build a thriving ecosystem of black-owned businessesBusiness 3",
      "originals": ["Service 7", "Service 8", "Service 9"],
      "contactNumber": "555-9012",
      "contactEmail": "business3@example.com",
      "username": "business3",
      "password": "password1",
      "isPortrait": true,
      "isAd": false,
      "store": "Mihai",
      saves: 158000,
    },
    {
      "id": 16,
      "image": "https://i8.amplience.net/i/jpl/jd_637232_e?qlt=92&w=750&h=531&v=1&fmt=auto",
      "title": "Food and Beverage",
      "businessName": "Boohoo",
      "address": "1234 First St, City, State, Zip",
      "description": "Passionate curator for black-owned businesses, prioritizing sustainability & social responsibility. Join me in creating an inclusive economy & supporting diverse entrepreneurs. Let's build a thriving ecosystem of black-owned businessesBusiness 4",
      "originals": ["Service 10", "Service 11", "Service 12"],
      "contactNumber": "555-3456",
      "contactEmail": "business4@example.com",
      "username": "business4",
      "password": "password1",
      "isPortrait": true,
      "isAd": false,
      "store": "Boohoo",
      saves: 1200000,
    },
    {
      "id": 17,
      "image": "https://cdn-img.prettylittlething.com/3/f/9/6/3f96423becddfc12c87f21b6f4795dbf6252c7c9_cnc6624_1.jpg?imwidth=400",
      "title": "Fashion and Clothing",
      "businessName": "Pretty Litle Things",
      "address": "5678 Second St, City, State, Zip",
      "description": "Passionate curator for black-owned businesses, prioritizing sustainability & social responsibility. Join me in creating an inclusive economy & supporting diverse entrepreneurs. Let's build a thriving ecosystem of black-owned businessesBusiness 5",
      "originals": ["Service 13", "Service 14", "Service 15"],
      "contactNumber": "555-6789",
      "contactEmail": "business5@example.com",
      "username": "business5",
      "password": "password1",
      "isPortrait": true,
      "isAd": false,
      "store": "Pretty Litle Things",
      saves: 543000,
    },
    {
      "id": 18,
      "image": "https://picsum.photos/700/700?random",
      "title": "Home and Decor",
      "businessName": "Digital Cats",
      "address": "9012 Third St, City, State, Zip",
      "description": "Passionate curator for black-owned businesses, prioritizing sustainability & social responsibility. Join me in creating an inclusive economy & supporting diverse entrepreneurs. Let's build a thriving ecosystem of black-owned businessesBusiness 6",
      "originals": ["Service 16", "Service 17", "Service 18"],
      "contactNumber": "555-2345",
      "contactEmail": "business6@example.com",
      "username": "business6",
      "password": "password1",
      "isPortrait": false,
      "isAd": false, 
      "store": "Digital Cats",
      saves: 14800000,
    },
    {
      "id": 19,
      "image": "https://picsum.photos/700/700?random",
      "title": "Health and Wellness",
      "businessName": "Tesco",
      "address": "3456 Fourth St, City, State, Zip",
      "description": "Passionate curator for black-owned businesses, prioritizing sustainability & social responsibility. Join me in creating an inclusive economy & supporting diverse entrepreneurs. Let's build a thriving ecosystem of black-owned businessesBusiness 7",
      "originals": ["Service 19", "Service 20", "Service 21"],
      "contactNumber": "555-5678",
      "contactEmail": "business7@example.com",
      "username": "business7",
      "password": "password1",
      "isPortrait": false,
      "isAd": false,
      "store" : "Tesco",
      saves: 45000
    }
  ],
  users: [
    {
      "id": 12,
      "image": "https://res.cloudinary.com/digital-cats/image/upload/v1680872017/Bellos/Ramadan_BOxes_1_juj7ww.png",
      "profileImage":"",
      "title": "Bellos Kitchen",
      "userName": "Naima ",
      "address": "123 Main St, City, State, Zip",
      "description": "Passionate curator for black-owned businesses, prioritizing sustainability & social responsibility. Join me in creating an inclusive economy & supporting diverse entrepreneurs. Let's build a thriving ecosystem of black-owned businessesBusiness 1",
      "originals": ["Service 1", "Service 2", "Service 3"],
      "contactNumber": "555-1234",
      "contactEmail": "business1@example.com",
      "username": "business1",
      "password": "password1",
      "isPortrait": false,
      "isAd": false,
      "store": "Bellos",
      saves: 5800000,

    },
    {
      "id": 13,
      "image": "https://cdn-img.prettylittlething.com/b/4/3/c/b43c85a2168c0954758b581879b968444dd3ac77_cnc5313_1.jpg",
      "profileImage":"",
      "title": "Digital Cats",
      "userName": "Ameen Ramjon",
      "address": "456 Main St, City, State, Zip",
      "description": "Passionate curator for black-owned businesses, prioritizing sustainability & social responsibility. Join me in creating an inclusive economy & supporting diverse entrepreneurs. Let's build a thriving ecosystem of black-owned businessesBusiness 2",
      "originals": ["Service 4", "Service 5", "Service 6"],
      "contactNumber": "555-5678",
      "contactEmail": "business2@example.com",
      "username": "business2",
      "password": "password1",
      "isPortrait": true,
      "isAd": false,
      saves: 850000,
    },
    {
      "id": 14,
      "image": "https://makeagency.co.uk/wp-content/uploads/2023/02/make-agency-web-trends2023-590x357.jpg",
      "profileImage":"",
      "title": "Beauty and Personal Care",
      "userName": "David Smith",
      "address": "789 Main St, City, State, Zip",
      "description": "Passionate curator for black-owned businesses, prioritizing sustainability & social responsibility. Join me in creating an inclusive economy & supporting diverse entrepreneurs. Let's build a thriving ecosystem of black-owned businessesBusiness 3",
      "originals": ["SEO ", " MARKETING", " WEBSITES"],
      "contactNumber": "555-9012",
      "contactEmail": "business3@example.com",
      "username": "business3",
      "password": "password1",
      "isPortrait": false,
      "isAd": false,
      "store": "Make Agency",
      saves: 3809900,
    },
    {
      "id": 15,
      "image": "https://images.pexels.com/photos/1400249/pexels-photo-1400249.jpeg?cs=srgb&dl=pexels-mihai-vlasceanu-1400249.jpg&fm=jpg",
      "profileImage":"",
      "title": "Beauty and Personal Care",
      "userName": "Mahitima Salasi",
      "address": "789 Main St, City, State, Zip",
      "description": "Passionate curator for black-owned businesses, prioritizing sustainability & social responsibility. Join me in creating an inclusive economy & supporting diverse entrepreneurs. Let's build a thriving ecosystem of black-owned businessesBusiness 3",
      "originals": ["Service 7", "Service 8", "Service 9"],
      "contactNumber": "555-9012",
      "contactEmail": "business3@example.com",
      "username": "business3",
      "password": "password1",
      "isPortrait": true,
      "isAd": false,
      "store": "Mihai",
      saves: 158000,
    },
    {
      "id": 16,
      "image": "https://i8.amplience.net/i/jpl/jd_637232_e?qlt=92&w=750&h=531&v=1&fmt=auto",
      "profileImage":"",
      "title": "Food and Beverage",
      "userName": "Sam Aremu",
      "address": "1234 First St, City, State, Zip",
      "description": "Passionate curator for black-owned businesses, prioritizing sustainability & social responsibility. Join me in creating an inclusive economy & supporting diverse entrepreneurs. Let's build a thriving ecosystem of black-owned businessesBusiness 4",
      "originals": ["Service 10", "Service 11", "Service 12"],
      "contactNumber": "555-3456",
      "contactEmail": "business4@example.com",
      "username": "business4",
      "password": "password1",
      "isPortrait": true,
      "isAd": false,
      "store": "Boohoo",
      saves: 1200000,
    },
    {
      "id": 17,
      "image": "https://res.cloudinary.com/dfhcjbewi/video/upload/v1662301050/Work/P1036113_yj5yzj.https://res.cloudinary.com/dfhcjbewi/image/upload/v1662301076/Work/P1036146_xeetyh.jpgmp4",
      "profileImage":"https://res.cloudinary.com/dfhcjbewi/image/upload/v1662300908/Carlos%20Tamale/P1036241_vbpzo0.jpg",
      "title": "Fashion and Clothing",
      "userName": "Carlos Tamale",
      "address": "5678 Second St, City, State, Zip",
      "description": "Passionate curator for black-owned businesses, prioritizing sustainability & social responsibility. Join me in creating an inclusive economy & supporting diverse entrepreneurs. Let's build a thriving ecosystem of black-owned businesses.",
      "originals": ["Service 13", "Service 14", "Service 15"],
      "contactNumber": "555-6789",
      "contactEmail": "business5@example.com",
      "username": "Carlos Tamale",
      "password": "password1",
      "isPortrait": false,
      "isAd": false,
      "store": "Pretty Litle Things",
      saves: 543000,
    },
    {
      "id": 18,
      "image": "https://picsum.photos/700/700?random",
      "profileImage":"",
      "title": "Home and Decor",
      "userName": "Digital Cats",
      "address": "9012 Third St, City, State, Zip",
      "description": "Passionate curator for black-owned businesses, prioritizing sustainability & social responsibility. Join me in creating an inclusive economy & supporting diverse entrepreneurs. Let's build a thriving ecosystem of black-owned businessesBusiness 6",
      "originals": ["Service 16", "Service 17", "Service 18"],
      "contactNumber": "555-2345",
      "contactEmail": "business6@example.com",
      "username": "business6",
      "password": "password1",
      "isPortrait": false,
      "isAd": false, 
      "store": "Digital Cats",
      saves: 14800000,
    },
    {
      "id": 19,
      "image": "https://picsum.photos/700/700?random",
      "profileImage":"",
      "title": "Health and Wellness",
      "userName": "Tesco",
      "address": "3456 Fourth St, City, State, Zip",
      "description": "Passionate curator for black-owned businesses, prioritizing sustainability & social responsibility. Join me in creating an inclusive economy & supporting diverse entrepreneurs. Let's build a thriving ecosystem of black-owned businessesBusiness 7",
      "originals": ["Service 19", "Service 20", "Service 21"],
      "contactNumber": "555-5678",
      "contactEmail": "business7@example.com",
      "username": "business7",
      "password": "password1",
      "isPortrait": false,
      "isAd": false,
      "store" : "Tesco",
      saves: 45000
    }
  ],
  categories: [
    "Beauty and Personal Care",
    "Fashion and Apparel",
    "Food and Beverage",
    "Home and Decor",
    "Jewelry and Accessories",
    "Music and Entertainment",
    "Sports and Fitness",
    "Technology and Gadgets",
    "Travel and Leisure"
  ]
}

export default data;